name: Scan with Skims

on:
  push:
  pull_request:

jobs:
  skims-scan:
    name: Run Fluid Attacks Skims Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Skims Scan in Strict Mode
        run: |
          echo "Starting Skims scan in --strict mode..."
          docker run --rm -v "$(pwd)":/scan_target fluidattacks/skims:latest skims --strict scan /scan_target
          echo "Skims scan completed. No vulnerabilities found in strict mode."
