name: Scan with Skims
on:
  push:
  pull_request:
jobs:
  skims-scan:
    name: Run Fluid Attacks Skims Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Skims Scan in Strict Mode
        id: skims-scan
        continue-on-error: true
        run: |
          echo "Starting Skims scan in --strict mode..."
          docker run --rm -v "$(pwd)":/scan_target -w /scan_target fluidattacks/skims:latest \
          skims scan .skims.yaml
          echo "Skims scan completed."

      - name: Check if CSV file was created
        run: |
          if [ -f "Fluid-Attacks-Results.csv" ]; then
            echo "CSV file found"
            ls -la Fluid-Attacks-Results.csv
          else
            echo "CSV file not found"
            ls -la
          fi

      - name: Upload Skims Scan Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: skims-vulnerability-report
            path: Fluid-Attacks-Results.csv
            retention-days: 7
            if-no-files-found: warn

      - name: Check Scan Results and Fail if Vulnerabilities Found
        run: |
          if [ -f "Fluid-Attacks-Results.csv" ]; then
            echo "Checking CSV file for vulnerabilities..."
            line_count=$(wc -l < Fluid-Attacks-Results.csv)
            if [ $line_count -gt 1 ]; then
              echo "❌ Security vulnerabilities found! Check the uploaded report."
              echo "Number of issues: $((line_count - 1))"
              exit 1
            else
              echo "✅ No vulnerabilities found."
            fi
          else
            echo "⚠️ No CSV report found - scan may have failed"
            exit 1
          fi
